# Generated by Django 4.0.2 on 2022-03-31 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_article_id_article_sno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
