# Generated by Django 4.0.2 on 2022-03-31 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('click', models.CharField(max_length=255)),
                ('event', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Pinned',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.article')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('profile', models.URLField(blank=True, null=True)),
                ('message', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.article')),
            ],
        ),
    ]
