# Generated by Django 4.0.2 on 2022-04-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_article_summary_alter_article_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=1000)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('Spotlight', 'Spotlight'), ('Academic', 'Academic'), ('Sports', 'Sports'), ('Campus', 'Campus')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
