# Generated by Django 4.0.2 on 2022-05-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_interviews_alter_article_tag_alter_comments_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interviews',
            new_name='Spotlight',
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('Academic', 'Academic'), ('Spotlight', 'Spotlight'), ('Sports', 'Sports'), ('Campus', 'Campus')], max_length=100, null=True),
        ),
    ]
