# Generated by Django 4.0.4 on 2022-06-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_rename_interviews_spotlight_alter_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='sno-<django.db.models.fields.AutoField>'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('Academics', 'Academics'), ('Opinion', 'Opinion'), ('Sci-Tech', 'Sci-Tech'), ('Spotlight', 'Spotlight'), ('General', 'General'), ('Insti Life', 'Insti Life')], max_length=100, null=True),
        ),
    ]
