# Generated by Django 4.0.4 on 2022-06-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_article_slug_alter_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='postViews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('Insti Life', 'Insti Life'), ('Opinion', 'Opinion'), ('Academics', 'Academics'), ('Spotlight', 'Spotlight'), ('Sci-Tech', 'Sci-Tech'), ('General', 'General')], max_length=100, null=True),
        ),
    ]
